### ISSUE TITLE
Gettin XR_ERROR_RUNTIME_FAILURE in OpenXR Developer Toolkit

### ISSUE THREAD

**Issue by Python-61** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#12]
I am getting the above error in my OpenXR Developer Toolkit when I install the OpenXR NIS Scaler, not into the default folder. After hours of uninstalling and reinstalling both the OpenXR Developer Toolkit and OpenXR NIS Scaler, I accidentally found this out. Frustrating! I just assumed that the OpenXR NIS Scaler would work from any folder.

Also, after a long time of trial and error, I have come to the conclusion that for the OpenXR Developer Toolkit to display that it is working correctly, I need Oculus set as the OpenXR runtime for my Quest 2. Not the OpenXR runtime that I can set in the OpenXR Developer Toolkit. I thought they would be interchangeable, apparently not so.

Anyway, when the OpenXR Developer Toolkit is displaying that it is working, I was installing the OpenXR NIS Scaler into a folder on another hard drive, the OpenXR Developer Toolkit then displayed the "XR_ERROR_RUNTIME_FAILURE" error.

Python-61

**Comment by mbucchia** [comment]
Thanks for the report. I think I had a release note about this at some point but it was accidentally removed from the Readme.

The software MUST be installed in a system folder such as Program Files for UWP applications such as the Developer Tools and MSFS to work.

I'll be sure to re-add this note somewhere. 

Also, there are some videos around on YouTube claiming that you must use the OpenXR Developer Tools - this is incorrect. These tools only work for Windows Mixed Reality headsets, not Oculus!

**Comment by Python-61** [comment]
I appreciate your reply and that this software is Beta.

Unfortunately, once I finally got it running, my VR frame rate in MSFS
dropped from a high of 33fps, with a consistent 30fps, to a horrible high
of 28fps to a consistent low of 22 to 25fps. This is without changing a
single setting inside MSFS.

Worst still, after uninstalling the scaler, my VR frame rates are stuck
low. I have run out of time for today to try and diagnose and fix this new
problem.

Python-61

**Comment by mbucchia** [comment]
> Worst still, after uninstalling the scaler, my VR frame rates are stuck low.

Sounds like you are having other issues unrelated to my software. 

If you not sure the program was uninstalled correctly, take a look at your registry (regedit) under `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1\ApiLayers\Implicit`. It should be empty.

If the key in the registry is empty and the files are gone from where you had installed it, then there is absolutely no chance this caused your issue.

Maybe you also installed an NVIDIA driver update around the same time? I've read on the official MSFS forum that the newest NVIDIA driver has performance issues.

**Comment by Python-61** [comment]
That key is not there, at all, so I assume that your software has been
fully uninstalled.

Nothing has changed since running MSFS yesterday. Anyway that is all I can
do for today. Won't have time to look again for a couple of days.

Python-61

**Comment by Python-61** [comment]
Good and bad news. I made time to have another go at fixing MSFS and have
restored it to its previous good behavior in VR. I forgot I had changed a
scaling setting in PC mode, which apparently affected VR mode. That really
shouldn't happen.

Anyway, seeing all was well I tried your NIS application again. This time
it had no effect at all, either raising or lowering my frame rate. So I
have uninstalled it again and will look out for the next update and try
again.

Python-61

**Comment by mbucchia** [comment]
What settings did you try (NIS scaling) and did you confirm it was functional (Ctrl+F1 to toggle between NIS and nearest filter - you should be able to see the difference in quality).

**Comment by Python-61** [comment]
I have tried again with the OpenXR NIS Scaler and it is working. Ctrl+F1
clearly shows that at the 50% Sharpness setting, there is an obvious
improvement in sharpness of the displayed graphics. Unfortunately, Ctrl+F1
also shows no variation to my FPS in MSFS, when on or off.

At least I can benefit from a sharper image in my Quest 2.

Finally, does the OpenXR NIS Scaler work with any other games?

Python-61

**Comment by mbucchia** [comment]
> Unfortunately, Ctrl+F1
also shows no variation to my FPS in MSFS, when on or off.

That's actually expected. CTRL-F1 does not disable upscaling, in only disable NIS. So the Sim will still render at the same resolution. The real FPS test is to compare between say 80% in-game render scale vs 80% NIS. In both cases the render resolution should the same, hence comparable.

> Finally, does the OpenXR NIS Scaler work with any other games?

Only OpenXR games. There arent many yet. For OpenVR games, please see a similar project:

https://github.com/fholger/openvr_fsr

**Comment by Python-61** [comment]
Just to clarify, I should change the render scale in MSFS to 80%, leave
OpenXR NIS Scaler at 100% and note the FPS when flying .

Then change MSFS render scale to 100%, shut down MSFS, change OpenXR NIS
Scaler to 80%, restart MSFS and again note the FPS when flying.

This will give me a comparison, which will show which combination gives the
best FPS when flying.

Python-61

**Comment by Python-61** [comment]
Got it working somewhat as intended, only getting 10% FPS boost when I
select 80% render scale in MSFS. Useful, if not the 30% boost others claim
to see.

Python-61

**Comment by mbucchia** [comment]
No work left on this.

**Comment by Python-61** [comment]
Thank you.
