### ISSUE TITLE
MSFS crash as soon as I turn VR on with NIS Scaler enabled

### ISSUE THREAD

**Issue by sbeuh34** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#15]
Hello, I'm facing MSFS crashes as soon as I switch to VR mode only when NIS Scaler is enabled. I will try to share as much information as possible about my configuration.

From Nvidia configuration panel:
> Nvidia drivers version: 497.12
> DirectX version running: 12
>Graphic card: Geforce RTX 3060 12goVram
>Global Settings:
> > All set to default and Image Scaling Disabled
>MSFS specific settings in Nvidia panel: All set to default values

From OpenXR development tools:
> Use lastest preview OpenXR runtime: ON
> Custom render scale: 100%
> Motion Reprojection: Disabled
>Runtime Version: 109.2111.23003

From OpenXR Nis Scaler (FS2020 - Microsoft Flight Simulator 2020):
> NIS Scaling 80%
> Sharpness 60%
> Enable screenshots Disabled

My Headset:
>HP Reverb G2

Windows Mixed Reality Settings
>Headset Display:
> >Headset Native Resolution: 4320x2160
> >Adjust screen resolution: 4320x2160 (best quality)
> >Image Frequency: 90Hz

My startup procedure: 
> Start my heaset and WMR
> Launch MSFS
> Start a flight
> Once in the cockpit toggle VR

Additional informations:
> Followed PieInTheSkyTour tutorial step by step for installation and configuration

If Enable NIS Scaling is checked when toggling VR in MSFS, I got an instant crash of MSFS
If it is not checked, I can go in VR and do my flight but of course without NIS Scaling.

Is there any log file (from NIS Scaler, WMR, or MSFS) or anything else that I could share to you in order to figure out what is causing the crash? 

Thank you for your tool, seems to be amazing from youtube video I saw!

**Comment by mbucchia** [comment]
Can you make sure you game is set to DX11? For now DX12 is not supported.

**Comment by sbeuh34** [comment]
Hello,
Thanks for reply. I'm definitly dumb, my game was on dx12. Invalid issue. Thanks a lot for your incredible tool!
