### ISSUE TITLE
Graphical artifacts

### ISSUE THREAD

**Issue by Lloydy86** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#16]
When using the tool after about 5-15 mins i start to get graphical artifacts in MSFS that dont go away until i restart the game. Im using a Nvidia rtx 3090 and a GP reverb G2 and tested with drivers 497.29, 497.09 and 496.76.   when disabling NIS in your app i don't get this problem.    the artifacts look like lots of small squares and appear mostly in clouds, trees and and the boarder of the planes glass.

**Comment by mbucchia** [comment]
Hello,

> when disabling NIS in your app i don't get this problem

Do you mean when disabling it from the configuration tool prior to starting the game?

Can you also try to use Ctrl+F1 in the game when it happens, this will switch between NIS and a nearest filter. Let me know if the artifacts still appear in nearest mode.

> that dont go away until i restart the game

Can you try to just leave and re-enter VR instead? Does it make the issue go away?

**Comment by Lloydy86** [comment]
Yes, when disabling it from the configuration tool prior to starting the game I dont get this issue.

Ctrl+F1 does not fix the issues.

leaving VR and going back to do and reentering VR does not fix the issue.  additionally once the glitch starts it persists into 2d mode also.  

also wanted to add that in addition to visual artifacts the games goes from super smooth to a lot of stutter.

I guess it could be a driver issue, what driver version do you use?  Also for the 5-10 mins prior to the the issue it looks amazing, never had VR so smooth prior to your tool, wanted to say thanks for your great work! to bad devs are too slow to implement stuff like this into their sim.

**Comment by mbucchia** [comment]
Glad to hear your issue is resolved (or at least identified). It did seem a little weird given your symptoms!
