### ISSUE TITLE
How to Increase OpenXR Resolution

### ISSUE THREAD

**Issue by matthewttt** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#17]
Hi mbucchia, good work man! Question: with the NIS scaler layer active, and my Quest 2 connected, the Open XR resolution showing in the OpenXR NIS Scaler configuration tool is 2064x2096. How/what determines that number? How could I increase it to say 3156x3088 and would it increase the sharpening ability? As it is, I get some sharpening but not much. Also, a lot of stutter. I have i7-10700KF CPU/32Gb memory and Nvidia RTX 2060 S/8GB memory. Thanks, Matthew

**Comment by mbucchia** [comment]
The OpenXR resolution is the one set via the Oculus tools. I don't own an Oculus headset so I don't know where that is set. The folks on https://forums.flightsimulator.com/c/virtual-reality are really good at this and they'll know how to answer.

If you are saying that you're already experiencing stutter, the I think increasing that resolution will only make things worse. But there too the folks on the forum have experimented a lot more than I have and should be able to help you.

**Comment by matthewttt** [comment]
Thanks, I'll try that

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
