### ISSUE TITLE
Stutters with Airlink

### ISSUE THREAD

**Issue by Knave49** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#18]
Since install the NIS Scaler, I seem to be getting brief, but regular stutters in VR.  I did notice that when running the configurator, I see a brief blink on the NIS slider every several seconds.  Not sure if this is normal.  

https://user-images.githubusercontent.com/97360901/148657054-8ebc2572-f478-429e-ab8c-fc68ac9640f6.mp4

**Comment by mbucchia** [comment]
The blinking is expected, the tool refreshes the resolution from the OpenXR runtime every 10 seconds. You should close the tool while you're not actively using it to configure anything.

**Comment by Knave49** [comment]
Thanks for the reply.  Can the refresh rate cause stutters, especially
while using AirLink?  It does seem to improve visuals. 

Sal Aliotta

On January 8, 2022, GitHub ***@***.***> wrote:
> The blinking is expected, the tool refreshes the resolution from the
> OpenXR runtime every 10 seconds. You should close the tool while
> you're not actively using it to configure anything.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/issues/18#issuecomment-
1008125201>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AXGZYBKX3IPFAIYUD2ZKGTLUVCH6VANCNFSM5LQ6B5EQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by mbucchia** [comment]
I don't own an Oculus devices and I've never used Airlink. So I really don't know. You're going to have to experiment! If you find interesting stuff please report back. Good luck!

**Comment by Knave49** [comment]
Will do .. thanks. 

On January 8, 2022, Matthieu Bucchianeri ***@***.***>
wrote:
> I don't own an Oculus devices and I've never used Airlink. So I really
> don't know. You're going to have to experiment! If you find
> interesting stuff please report back. Good luck!
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/issues/18#issuecomment-
1008216576>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AXGZYBOWKWDHBOYBI6C4RN3UVDYLNANCNFSM5LQ6B5EQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by mbucchia** [comment]
Closing as won't fix in this project. The OpenXR-Toolkit will not rely on the external config tool - hence not subject to the issue.
