### ISSUE TITLE
App goes into 'Not Responding' loop at startup

### ISSUE THREAD

**Issue by imacmill** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#20]
OpenXR-NIS-Scaler-BETA1-Hotfix1
Windows 10, DX11 (all up to date as of Jan 12, 2022).
GTX-1080 with NVidia Driver v.497.29

When I start OpenXR NIS Scaler, the main dialog displays but immediately goes into a 'Not Responding' (as seen in window title bar) loop whereby the dialog becomes unresponsive for about 5 seconds, then briefly comes back to life for about 1 second, then goes back to 'Not Responding'. Repeats over and over.

The 'OpenXR Resolution:' shows blank (no text) and it says 'NIS Scaler layer is active' in green text at the top.

I am able to close the app during the 1-second intervals where it is responsive.

**Comment by dataslug1** [comment]
I have just installed the Beta version and have the same problem.  Windows 10, 3090

I had previously used the Alpha 4 without issue.  I ran the alpha uninstaller before installing the beta.

**Comment by mbucchia** [comment]
Thank you both for the report. The configuration tool will be sort of removed in the next version (since the settings will be integrated in an on-screen display you can control directly inside the game and without having to remove your headset).

You will need to wait for this new version to be released later this month. Thanks!

**Comment by dataslug1** [comment]
No problem, I will return to the previous version then.  Thanks for your work !

**Comment by imacmill** [comment]
> Thank you both for the report. The configuration tool will be sort of removed in the next version (since the settings will be integrated in an on-screen display you can control directly inside the game and without having to remove your headset).
> 
> You will need to wait for this new version to be released later this month. Thanks!

Thanks for the reply.

FWIW, I *think* the reported bad behavior is dependent upon what version of OpenXR is active on the system, Steam, Oculus or WMR. Not fully confirmed, so take it with a grain of salt.

**Comment by mbucchia** [comment]
Yes I'm pretty sure you are right :)

I'm doing something that I now realize is a bit fishy, and it worked OK with my setup (WMR) but apparently other runtimes may be be more "sensitive".

**Comment by mbucchia** [comment]
Closing as won't fix in this project. The OpenXR-Toolkit will not rely on the external config tool - hence not subject to the issue.

**Comment by dataslug1** [comment]
> I'm doing something that I now realize is a bit fishy, and it worked OK with my setup (WMR) but apparently other runtimes may be be more "sensitive".

If it helps I have the problem and I'm using SteamVR (Quest2).  As mentioned no problem with the alpha version.
