### ISSUE TITLE
In game sharpening

### ISSUE THREAD

**Issue by Knave49** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#21]
Hi .. thanks for providing this tool.  However, I noticed that CTRL + F1 does toggle the scaler which clearly shows better results, but CTRL + F2 (or down arrow) and CTRL + F3 (or up arrow) does not seem to increase or decrease the sharpness.  Is there anything I can do?

**Comment by mbucchia** [comment]
I don't see why it wouldn't work. It might be subtle to see in some scenes. Can you look at objects far away? This is where the difference is most noticeable.

**Comment by Knave49** [comment]
Hi .. yes, I can now see the difference when focusing on objects in the
distance.   Thank you!  Will the app maintain this sharpness level even
after I close MSFS and shut down headset?  I noticed the scale shown in
the config tool stays the same.  The other question I have is:  should
NIS scaling be set to equal Open XR Resolution?  If not, is there an
ideal % that would give best visuals?  I am attaching my settings as
reference. I appreciate your time and advice.  Regards,

Sal A



On January 16, 2022, Matthieu Bucchianeri ***@***.***>
wrote:
> I don't see why it wouldn't work. It might be subtle to see in some
> scenes. Can you look at objects far away? This is where the difference
> is most noticeable.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/issues/21#issuecomment-
1013936823>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AXGZYBLQ23Y6QKWGKTYPWKDUWMLYDANCNFSM5MDBJZOA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by mbucchia** [comment]
>  Will the app maintain this sharpness level even after I close MSFS and shut down headset?  I noticed the scale shown in the config tool stays the same. 

In this version, the changes made with Ctrl-F2/F3 are not permanent. You need to make the corresponding changes using the slider in the configuration tool. You can look at the log file (`%LocalAppData%\XR_APILAYER_NOVENDOR_nis_scaler.log`) which tells you the sharpness live (look at the last line in the file that says `sharpness=<some value>`. This won't be a problem in the next version.

> The other question I have is:  should NIS scaling be set to equal Open XR Resolution?  If not, is there an
ideal % that would give best visuals?  I am attaching my settings as reference. I appreciate your time and advice. 

Sorry I cannot help you with tweaking. The forum is the best place for that: https://forums.flightsimulator.com/t/openxr-nis-upscaling-software-release-thread/482927

**Comment by Knave49** [comment]
Okay. Thanks for your help.

Sal Aliotta

On January 17, 2022, GitHub ***@***.***> wrote:
> > Will the app maintain this sharpness level even after I close MSFS
> > and shut down headset? I noticed the scale shown in the config tool
> > stays the same.
> >
>
> In this version, the changes made with Ctrl-F2/F3 are not permanent.
> You need to make the corresponding changes using the slider in the
> configuration tool. You can look at the log file
> (%LocalAppData%\XR_APILAYER_NOVENDOR_nis_scaler.log) which tells you
> the sharpness live (look at the last line in the file that says
> sharpness=<some value>. This won't be a problem in the next version.
>
> > The other question I have is: should NIS scaling be set to equal
> > Open XR Resolution? If not, is there an
> >  ideal % that would give best visuals? I am attaching my settings as
> > reference. I appreciate your time and advice.
> >
>
> Sorry I cannot help you with tweaking. The forum is the best place for
> that: <https://forums.flightsimulator.com/t/openxr-nis-upscaling-
> software-release-thread/482927>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/issues/21#issuecomment-
1015021605>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AXGZYBOV2N64TTSRRAXTPKDUWTHSFANCNFSM5MDBJZOA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
