### ISSUE TITLE
NIS Scaler Program in Loop

### ISSUE THREAD

**Issue by FrankWLeisten** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#25]
When I turned on Game Mode in Win 11 and started Pimax PiTools, SteamVR then MSFS2020 and closed all Programs to change settings in NIS Scaler the NIS Scaler just opened and ran in a loop, could never change any settings.  NIS Scaler worked fine when WIN 11 Game mode was turned off. Had to uninstall SteamVR and NIS scaler and reinstall.  Turned off Win 11 Game mode and program is working fine again.  SUPER program and Thank You as it was needed in the VR community.

**Comment by mbucchia** [comment]
Thanks for the report. 

This is same as #20 and it will be resolved in the next version.
