### ISSUE TITLE
Light Alignment and Instrument/HUD Coloring

### ISSUE THREAD

**Issue by MikeMarcus** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#6]
In NIS mode, certain lights seem to be off a bit.  Example, when landing, the 4 red/white lights at the beginning of the runways display the red lights slightly off center from the white lights.  Toggling using CTRL-F1, the alignment seems to correct itself, though the lower level processing makes everything blurry when that's done.

Also, the HUD text (and others) are a lighter color when NIS is engaged and toggling out of NIS using CTRL-F1 puts the colors back to where they were pre-NIS.

This is not likely due to the tool, but I thought I'd report it just in case it does have some sort of impact on graphic performance.  I didn't see any of this happening in Alpha 4, BTW.  Thanks so much!

**Comment by mbucchia** [comment]
Hi Mike, can you try this version and compare?

https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/raw/revert-to-nis-100/Setup/Output/OpenXR-NIS-Scaler-BETA1-NIS-1.0.0.msi

Thanks!!

**Comment by mbucchia** [comment]
I believe this is indeed an issue with the new NIS SDK 1.0.1. I am reverting the change. Please try this other version to make sure it does indeed resolve the issue!

**Comment by MikeMarcus** [comment]
That worked, everything was lined up just fine.  Thank you!!
