### ISSUE TITLE
In game scale taking wrong value?

### ISSUE THREAD

**Issue by octo1234** [mbucchia/XR_APILAYER_NOVENDOR_nis_scaler#7]
Hi Just to say keep up the good work.

I notice that NIS scaling slider results in say 60% of the OpenXR resolution but the output in game takes the scaled down resolution

e.g. openxr @150% = 3864x3784
NIS @ 60% = 2320x2270

FS in game @100 now = the downsampled res not the upscaled res (2320x2270)

So the image takes a hit because its displaying at a reduced res.

to keep it looking good I am having to compensate by upping OpenXR scale to bring the game back up to a nice resolution.

or have up the in game scaling to compensate for the loss.

If I'm correct the in game res should be openXR res which has been rendered at 60% and upsampled to openXR res again?

Looking forward to future releases - please let me know if I'm doing it wrong

**Comment by mbucchia** [comment]
The in-game resolution displayed is the one before NIS up-scaling, hence 60% of the OpenXR resolution in your case. This is the goal of NIS: request the game to render at a lower resolution, then perform up-scaling to match the screen resolution (well here the OpenXR resolution).

The game is not aware that NIS up-scaling is happening, hence will only show the resolution pre-up-scaling. This is expected. The true output resolution after NIS is the OpenXR one.

60% is quite an aggressive setting, hence the lower quality. I would suggest to try something higher. Many people have reported using 80-90% with an OpenXR scale at 100%-125%.

**Comment by octo1234** [comment]
Thanks for your response, I was expecting the XR value to show up in the game not the NIS scale, thanks for clarifying.

My figures are just an example to try not what I'll stick with (although strangely did give good vis and FPS AMD 6900xt).

I'll do some testing and screen grabs - thx again for providing this tool.

P.S. will it ever be able to work in DX12 (when the game gets it working) or is it fundamentally a DX11 thing

**Comment by mbucchia** [comment]
DX12 will be supported in the future.

Thank you for your support!
